# Generated by Django 3.0.5 on 2020-04-26 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investments',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='investments',
            old_name='user_id',
            new_name='user',
        ),
    ]
